spring:
  application:
    name: spring-boot-demo

info:
  app:
    name: Spring Boot Demo
    type: Spring Boot
    java: 
      version: 8

 
server:
  port: 8080

management:
  endpoint:
    health:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*" 
        
     
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

