spring:
  application:
    name: spring-boot-demo
  profiles:
    active: dev

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost

info:
  app:
    name: Spring Boot Demo
    type: Spring Boot
    java: 
      version: 8

 
server:
  port: 8080

management:
  endpoint:
    health:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*" 
        

