version: 2.1

orbs:
  maven: circleci/maven@0.0.12
  heroku: circleci/heroku@1.0.1

jobs:
      build:
        docker:
          # specify the version you desire here
          - image: circleci/openjdk:8-jdk

          # Specify service dependencies here if necessary
          # CircleCI maintains a library of pre-built images
          # documented at https://circleci.com/docs/2.0/circleci-images/
          # - image: circleci/postgres:9.4

        working_directory: ~/repo

        environment:
          # Customize the JVM maximum heap limit
          MAVEN_OPTS: -Xmx3200m

        steps:
          - checkout

          # Download and cache dependencies
          - restore_cache:
              keys:
                - v1-dependencies-{{ checksum "pom.xml" }}
                # fallback to using the latest cache if no exact match is found
                - v1-dependencies-

          - run: mvn dependency:go-offline

          - save_cache:
              paths:
                - ~/.m2
              key: v1-dependencies-{{ checksum "pom.xml" }}

          # run tests!
          - run: mvn integration-test
          
          - run:
             name: Build Docker image
             command: docker build -t upadhyaybs/spring-boot-demo:latest
          - run:
              name: Push to DockerHub
              command: |
                docker login -u$DOCKERHUB_LOGIN -p$DOCKERHUB_PASSWORD
                docker push $DOCKERHUB_LOGIN/spring-boot-demo:1.0.0
          - run:
                name: Setup Heroku
                command: bash .circleci/setup-heroku.sh # run a script to set up Heroku
          - run:
                name: Deploy to Heroku
                command: |
                  git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master
